NetworkIOMeter: convert packets to per second
htop-dev/htop pull request #1128
Opened 2022-11-07 21:04 UTC by eworm-de

We should normalize the packets as well...

2022-11-08 00:21 UTC, BenBE approved these changes

2022-11-08 19:06 UTC, BenBE requested changes
I meant it that way around. I hope I didn't screw up with the intermediate units.

Please squash/fixup those changes into your second commit.

2022-11-08 19:06 UTC, BenBE commented on NetworkIOMeter.c
> +         diff /= ONE_K; /* Meter_humanUnit() expects unit in kilo */
Same as above:

```suggestion
         diff /= passedTimeInMs; /* convert to B/ms */
         diff = (1000 * diff) / ONE_K; /* convert to KiB/s */
```

2022-11-08 19:57 UTC, eworm-de commented on NetworkIOMeter.c
> +         diff /= ONE_K; /* Meter_humanUnit() expects unit in kilo */
But dividing at the beginning to get bytes per **millisecond** is the worst thing for precision, no?

2022-11-11 07:16 UTC, Explorer09 commented on NetworkIOMeter.c
> +         diff /= ONE_K; /* Meter_humanUnit() expects unit in kilo */
I don't get this either. If rounding to bytes per second is possible, there is no sense to round to bytes per _millisecond_ in the first place.

2022-12-06 13:57 UTC, merged