Linux + PCP: Add private memory size column
htop-dev/htop pull request #1336
Opened 2023-11-24 21:29 UTC by BowDown097

Private memory size is a metric supported by other tools like [System Monitoring Center](https://github.com/hakandundar34coding/system-monitoring-center) and [System Informer](https://systeminformer.sourceforge.io/). It is also a decently close measurement of the "real" memory usage of a process, like PSS.

Note that it is calculated by subtracting the shared memory size from the RSS, which won't always provide the exact real value, but it is a very close estimation an overwhelming majority of the time. Getting the real value appears to involve some querying of the kernel which is very slow for heavy processes, which is just unnecessary.

Would appreciate some testing for PCP, I can't do it because I'm not on systemd, which it requires. Not sure if what I did for it works properly, considering I have to multiply the shared memory by the page size in the Linux code.

2023-11-24 22:20 UTC, BenBE requested changes

2023-11-24 22:20 UTC, BenBE commented on linux/LinuxProcessTable.c
> +
```suggestion

      process->m_priv = process->super.m_resident - (process->m_share * host->pageSizeKB);
   }

```

2023-11-26 21:49 UTC, natoscott approved these changes
@BowDown097 looks good - I had to stare at the LinuxProcessTable.c units handling a little, but I think you've got it spot on.

PCP doesn't rely on systemd FWIW (predating it by at least 10 years) - its probably just the Debian packaging enforcing that nowadays for simplicity sake.  I'm sure that packaging could be made to work either way if anyone's keen.

I see from your diff that we're missing a CGROUP entry in pcp/ProcessField.h now - I'll follow up with that addition.

2023-11-26 22:22 UTC, natoscott requested changes

2023-11-26 22:22 UTC, natoscott commented on pcp/ProcessField.h
> +   M_PRIV = 129,                 \
Please update this to 130 now (see #1339 for context).

2023-11-27 03:54 UTC, merged