linux: harden terminal parsing
htop-dev/htop pull request #1430
Opened 2024-04-02 17:33 UTC by cgzones

Handle corrupted data in /proc/tty/drivers, either via injection or buffer truncation.

2024-04-03 09:15 UTC, BenBE requested changes
The overall routine could accept some more visual structure as it's currently hard to read in the way it is written. Also, some comment explaining the format to be parsed doesn't hurt.

2024-04-03 09:15 UTC, BenBE commented on linux/LinuxProcessTable.c
> +   unsigned int allocd = 10;
Be consistent about the type. Preferably `size_t`.

2024-04-05 17:32 UTC, BenBE commented on linux/LinuxProcessTable.c
> +      if (!at) goto finish;    // bail out on truncation
Avoid single-line if statements.

Also maybe leave some space after each block to group the various segment of the parsed line …

2024-04-06 23:15 UTC, BenBE approved these changes
LGTM. Minor style note.

2024-04-06 23:15 UTC, BenBE commented on linux/LinuxProcessTable.c
> +                  goto finish;    // bail out on truncation
Indentation.

2024-04-08 16:15 UTC, cgzones commented on linux/LinuxProcessTable.c
> +                  goto finish;    // bail out on truncation
fixed

2024-04-08 16:53 UTC, BenBE approved these changes

2024-04-13 19:38 UTC, merged