Fix strace issue
htop-dev/htop pull request #1529
Opened 2024-08-29 15:17 UTC by xzyjj

Fixed the issue that the CPU is fully loaded due to the process exiting tracked by strace.

Reproduce the process:
![gif](https://raw.githubusercontent.com/xzyjj/misc/7ce65bea29bb5e879683ac86194e1b90535d9f6b/htop/1.gif)

2024-08-29 22:04 UTC, Explorer09 commented on TraceScreen.h
> +   bool status;
The name "status" is unreadable.

2024-08-29 22:05 UTC, Explorer09 commented
Didn't get what you are actually trying to solve. What is the error or problem you are facing? And how to reproduce it?

2024-08-30 04:44 UTC, xzyjj commented
> Didn't get what you are actually trying to solve. What is the error or problem you are facing? And how to reproduce it?

Reproduction:
1. Execute `sleep 100`.
2. Open "htop" and find the `sleep 100` process, then press "s" to trace it.
3. "Ctrl-C" to end `sleep 100`

2024-08-30 08:01 UTC, BenBE commented
Please give this a read-through: https://marker.io/blog/how-to-write-bug-report

Those information should normally appear in the top-most post, where they are easy to find. You can edit your initial post to update these information.

And while I have a hinch what you are talking about, I'll ask you to be precise in your bug report/pull request first to avoid misunderstandings about the scope of what you are trying to achieve.

2024-09-04 09:03 UTC, BenBE requested changes

2024-09-04 09:03 UTC, BenBE commented on TraceScreen.c
> +     select(STDIN_FILENO + 1, &fds_in, NULL, NULL, &tv_in);
This somewhat duplicates the code below that is used for regular setup for the `fd_set`.

I think, we can achieve the same effect by doing the following:
1. Uncomment the `FD_SET(STDIN_FILENO, &fds);` line below
2. Only set `FD_SET(fd_strace, &fds);` IFF `this->strace_active` is still set (cf. note re naming of `status`)
3. Do the `select` on `MAXIMUM(STDIN_FILENO, fd_strace) + 1` for the max fd argument.

2024-09-04 09:03 UTC, BenBE commented on TraceScreen.c
> +       return;
Unnecessary `return;` statement.

2024-09-06 18:32 UTC, Explorer09 reviewed
Please follow the coding style of htop and indent with three spaces. (Yeah, not many projects use three-space indents, but htop is an exception here.)

2024-09-06 18:43 UTC, BenBE commented on TraceScreen.c
> +     select(STDIN_FILENO + 1, &fds_in, NULL, NULL, &tv_in);
Proposed patch:

```diff
diff --git a/TraceScreen.c b/TraceScreen.c
index ce4db089..6e0be59c 100644
--- a/TraceScreen.c
+++ b/TraceScreen.c
@@ -135,30 +135,20 @@ err:
 static void TraceScreen_updateTrace(InfoScreen* super) {
    TraceScreen* this = (TraceScreen*) super;
 
-   if (!this->strace_alive) {
-     fd_set fds_in;
-     FD_ZERO(&fds_in);
-     FD_SET(STDIN_FILENO, &fds_in);
-
-     struct timeval tv_in = { .tv_sec = 1 };
-     select(STDIN_FILENO + 1, &fds_in, NULL, NULL, &tv_in);
-
-     return;
-   }
-
-   char buffer[1025];
-
    int fd_strace = fileno(this->strace);
-   assert(fd_strace != -1);
 
    fd_set fds;
    FD_ZERO(&fds);
-// FD_SET(STDIN_FILENO, &fds);
-   FD_SET(fd_strace, &fds);
+   FD_SET(STDIN_FILENO, &fds);
+   if (this->strace_alive) {
+      assert(fd_strace != -1);
+      FD_SET(fd_strace, &fds);
+   }
 
    struct timeval tv = { .tv_sec = 0, .tv_usec = 500 };
-   int ready = select(fd_strace + 1, &fds, NULL, NULL, &tv);
+   int ready = select(MAXIMUM(STDIN_FILENO, fd_strace) + 1, &fds, NULL, NULL, &tv);
 
+   char buffer[1025];
    size_t nread = 0;
    if (ready > 0 && FD_ISSET(fd_strace, &fds))
       nread = fread(buffer, 1, sizeof(buffer) - 1, this->strace);
```

2024-09-06 18:45 UTC, BenBE commented on TraceScreen.c
> +       this->strace_alive = false;
Indentation
```suggestion
      if (this->strace_alive && waitpid(this->child, NULL, WNOHANG) != 0)
         this->strace_alive = false;
```

2024-09-18 21:43 UTC, BenBE approved these changes

2024-09-18 21:44 UTC, merged