Fix "stdscr" configure failure & ncursest support
htop-dev/htop pull request #1558
Opened 2024-10-19 04:29 UTC by Explorer09

The first two commits should be enough to fix the issue of #1548. But I plan to add some other improvements to make ncurses detection more robust. Notably we could add ncursest and ncursestw into the search list.

2024-10-19 08:41 UTC, BenBE requested changes
LGTM.

Document the `#if defined(HAVE_CONFIG_H)` to be used for reference inside `configure.ac`.

Also, if not done, have the ncursest specific changes re macros and the `ProvideCurses` changes live inside separate commits (though that already seems to be the case AFAICS).

2024-10-25 14:19 UTC, BenBE commented on configure.ac
> +#endif
I think you got the check inverted by accident …

```suggestion
#ifdef _XOPEN_SOURCE_EXTENDED
#undef _XOPEN_SOURCE_EXTENDED
#endif
```

2024-10-25 14:20 UTC, BenBE commented on configure.ac
> +   AC_MSG_FAILURE([there are problems with the curses header])])
```suggestion
   AC_MSG_FAILURE([there are problems with the curses header])
])
```

2024-10-25 21:29 UTC, BenBE commented on configure.ac
> +#endif
TIL. Please add a small note about this to document this somewhat. TIA.

2024-10-26 08:33 UTC, BenBE commented on configure.ac
> +   with _XOPEN_SOURCE */
Can be one line IMO.

```suggestion
[/* Enables XPG4v2 (SUSv1) interfaces if they are not enabled already with _XOPEN_SOURCE */
```

2024-10-27 16:55 UTC, Explorer09 commented
@BenBE

I have a idea when trying to improve configure in detecting ncurses header, but am not sure whether such a change is acceptable:

```diff
--- a/ProvideCurses.h
+++ b/ProvideCurses.h
@@ -16,16 +16,13 @@ in the source distribution for its full text.
 
 // IWYU pragma: begin_exports
 
-#if defined(HAVE_NCURSESW_CURSES_H)
-#include <ncursesw/curses.h>
-#elif defined(HAVE_NCURSES_NCURSES_H)
-#include <ncurses/ncurses.h>
-#elif defined(HAVE_NCURSES_CURSES_H)
-#include <ncurses/curses.h>
-#elif defined(HAVE_NCURSES_H)
-#include <ncurses.h>
-#elif defined(HAVE_CURSES_H)
-#include <curses.h>
+// The CURSES_HEADER_NAME macro may be defined by configure script to any of these:
+// <ncursesw/curses.h>
+// <ncurses/curses.h>
+// <ncurses.h>
+// <curses.h>
+#if defined(CURSES_HEADER_NAME)
+#include CURSES_HEADER_NAME
 #endif
 
 #ifdef HAVE_LIBNCURSESW
```

Instead of having a lot of boolean `HAVE_*CURSES_H` macro tokens, I think it would be better to have one token for curses/ncurses header name. This form of include directive is supposed to work with any C89-compliant compiler, but programmers might be unfamiliar with this form of include.

2024-10-27 16:59 UTC, BenBE commented
I considered it briefly when that header was created, but decided against it, as we hate the ProvideCurses.h anyway to deal with all the other aspects of curses that come bundled with terminal control stuff. And since you get those booleans for free™ from autoconf there's no real reason not using them in favour of some little-used feature of the pre-processor. So keep it as-is.

2024-10-27 23:46 UTC, Explorer09 commented
> I considered it briefly when that header was created, but decided against it, as we hate the ProvideCurses.h anyway to deal with all the other aspects of curses that come bundled with terminal control stuff. And since you get those booleans for free™ from autoconf there's no real reason not using them in favour of some little-used feature of the pre-processor. So keep it as-is.

The problem is, the list of possible header names for ncurses is non-exhaustive. We  only check header names that are common in distributions (`<ncursesw/curses.h>`, `<ncurses.h>`, etc.), but I've experimented with ncurses' configure (upstream), and it technically allows builders to specify any suffix for the library and header directory. So the header could be `ncurseswfoo/curses.h` (if ncurses is configured with `--with-extra-suffix=foo`), `ncurseswbar/curses.h` (if `--with-extra-suffix=bar`) and so on.

I know these are custom builds and niche use cases, but as I introduced `--with-curses=XXX` in htop's configure, I think I should allow builders to specify custom header for ncurses (to free them from needing to hack the ProvideCurses.h). It won't be a configure option, but a `CPPFLAGS='-DCURSES_HEADER_NAME=<ncurseswfoo/curses.h>'` override.

2024-10-28 08:10 UTC, BenBE commented
People who mess around with the header names may also just mess around with the code at that point. I doubt most programs using (n)curses at that point would even compile properly with these custom header names. That's some additional complexity added that doesn't provide reasonable benefit for the average case or is common enough to warrant going that extra kilometer.

People messing with their header names can feel lucky, that it's basically just one place they have to mess with in our code …

2024-11-02 10:03 UTC, Explorer09 commented
I think I would defer the header detection changes to another PR. The rest of the changes are ready.

2024-12-14 14:58 UTC, merged