Show trees with commands matching regex
htop-dev/htop pull request #219
Opened 2020-10-06 14:28 UTC by layderv

For this PR see: https://github.com/hishamhm/htop/issues/836#issuecomment-480027645

2020-10-06 15:46 UTC, fasterit commented on Settings.h
> +Released under the GNU GPL, see the COPYING file
rebase to HEAD please

2020-10-06 15:53 UTC, fasterit requested changes
I think this should integrate with the Filter functionality (F4 key), so that -F pre-sets a filter that can be cleared / amended in the UI. If that filter is regex, it should be regex in both use cases to not confuse users.
To me just plain string matching would be fine as well.

2020-10-06 20:31 UTC, layderv commented
> I think this should integrate with the Filter functionality (F4 key), so that -F pre-sets a filter that can be cleared / amended in the UI. If that filter is regex, it should be regex in both use cases to not confuse users.
> To me just plain string matching would be fine as well.

@fasterit Your comment make sense, this PR implements it. (By "-F pre-sets..." I think you meant "-P" as in the option.)

2020-10-07 07:18 UTC, fasterit commented
> @fasterit Your comment make sense, this PR implements it. (By "-F pre-sets..." I think you meant "-P" as in the option.)

No, I meant -F / --filter as that is consistent with the existing Filter (F4) GUI option.

2020-10-07 07:19 UTC, fasterit commented
The second iteration looks good except for

- Old license header (work of a fresh master / HEAD please)
- Command line flag should be -F / --filter
- Man page needs update

2020-10-07 08:10 UTC, layderv commented
@fasterit updated, thank you for the comments

2020-10-07 08:35 UTC, closed without merging

2020-10-07 08:36 UTC, fasterit commented
@layderv Excellent PR. Merged. Thank you very much.

2020-10-07 09:16 UTC, layderv commented
@fasterit would it be possible to approve the PR also? :)

2020-10-07 09:23 UTC, fasterit commented
I can't click approve on a PR that is already merged and thus closed.
Merging is the best approval you can get as it confirms the quality of your work.

2020-10-07 09:34 UTC, layderv commented
@fasterit ok, I was asking because for the hacktoberfest the PR is pending with reason "Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it" (and I believe the update should happen within seconds). Not sure why, but no problem :)

2020-10-07 09:46 UTC, fasterit commented
hm, "your PR by merging it". I've add the label, just in case.

2020-10-07 09:54 UTC, layderv commented
It worked, thank you! @fasterit