Add xReadfile wrapper for reading small to medium size files
htop-dev/htop pull request #341
Opened 2020-11-25 19:57 UTC by cgzones

Inspired by proposed Linux syscall

Avoid file descriptor leaks like 4af8c63f

2020-11-25 20:53 UTC, BenBE commented
Is it intentional that this does not allow to detect the file being too large?

What about `openat` support?

2020-11-26 19:21 UTC, cgzones commented
> Is it intentional that this does not allow to detect the file being too large?

Yes.
One can check if the return value equals the passed `count`, then the file is probably bigger (except it has unlikely the size `count`).
But the current code this wrapper replaces does not check for this case and for procfs files we assess what maximum size they have under normal circumstances.

> What about openat support?

Will come if #321 gets accepted.

2020-11-28 17:44 UTC, BenBE commented on Compat.c
> +   }
Extract to `xReadFD` for reuse in `xReadfileat` …

2020-11-28 17:49 UTC, BenBE commented on linux/LinuxProcessList.c
> +   buf[r] = '\0';
What about making the NUL termination part of the xReadfile API? I.e. internally ensured before terminating that the byte following the last index written in buffer is forced to `\0`?

2020-11-28 18:30 UTC, BenBE requested changes

2020-11-28 18:30 UTC, BenBE commented on XUtils.c
> +         ((char*)buffer)[alreadyRead] = '\0';
Avoid buffer overflow:
```suggestion
         if (count)
            ((char*)buffer)[alreadyRead] = '\0';
```

2020-11-28 18:37 UTC, cgzones commented on XUtils.c
> +         ((char*)buffer)[alreadyRead] = '\0';
there is previously the line `count--; // reserve one for null-terminator`.

Or should we check
```c
ssize_t xReadfile(const char* pathname, void* buffer, size_t count) {
   if (count == 0)
      return -EINVAL;
   ...
```
?

2020-11-28 18:43 UTC, BenBE commented on XUtils.c
> +         ((char*)buffer)[alreadyRead] = '\0';
Unconditionally decrementing causes `MAX_INT` to be read, which is likely undesired as well. But decrementing the `count` on entry is quite a good solution. So return `-EINVAL` on `!count` before decrementing it. Didn't notice the decrement when I initially read through the source.

2020-11-28 19:15 UTC, cgzones commented
Got a crash:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==34090==ERROR: AddressSanitizer: SEGV on unknown address 0x03e80000852a (pc 0x7ff3dd3bcfe1 bp 0x7ffe38245970 sp 0x7ffe38244f40 T0)
==34090==The signal is caused by a READ memory access.
    #0 0x7ff3dd3bcfe1 in raise nptl/../sysdeps/unix/sysv/linux/raise.c:51:1
    #1 0x4ed427 in CRT_handleSIGSEGV /home/christian/Coding/workspaces/htop/CRT.c:894:4
    #2 0x7ff3dd3bd13f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1413f)
    #3 0x7ff3dd254082  string/../sysdeps/x86_64/multiarch/../strchr.S:31
    #4 0x43cab8 in strchr (/home/christian/Coding/workspaces/htop/htop+0x43cab8)
    #5 0x57632b in LinuxProcessList_readStatFile /home/christian/Coding/workspaces/htop/linux/LinuxProcessList.c:351:18
    #6 0x56f201 in LinuxProcessList_recurseProcTree /home/christian/Coding/workspaces/htop/linux/LinuxProcessList.c:1330:13
    #7 0x567c6a in ProcessList_goThroughEntries /home/christian/Coding/workspaces/htop/linux/LinuxProcessList.c:1905:4
    #8 0x535c05 in ProcessList_scan /home/christian/Coding/workspaces/htop/ProcessList.c:346:4
    #9 0x53e803 in checkRecalculation /home/christian/Coding/workspaces/htop/ScreenManager.c:108:7
    #10 0x53bfc8 in ScreenManager_run /home/christian/Coding/workspaces/htop/ScreenManager.c:159:10
    #11 0x4fefe7 in main /home/christian/Coding/workspaces/htop/htop.c:336:4
    #12 0x7ff3dd1ddcc9 in __libc_start_main csu/../csu/libc-start.c:308:16
    #13 0x4278f9 in _start (/home/christian/Coding/workspaces/htop/htop+0x4278f9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV nptl/../sysdeps/unix/sysv/linux/raise.c:51:1 in raise
==34090==ABORTING
```

Checking on master...

2020-12-02 19:39 UTC, BenBE approved these changes

2020-12-02 19:39 UTC, merged