Add Linux cwd process column
htop-dev/htop pull request #345
Opened 2020-11-26 19:32 UTC by cgzones

Related: #344

2020-11-26 19:47 UTC, BenBE requested changes
What's the reasoning for renaming `flags` to `processFlags` for this PR?

2020-11-26 19:47 UTC, BenBE commented on linux/LinuxProcess.h
> +#define PROCESS_FLAG_LINUX_CWD      0x10000
Cf. #238.

2020-11-26 19:47 UTC, BenBE commented on linux/LinuxProcessList.c
> +   ssize_t r = readlink(filename, pathBuffer, sizeof(pathBuffer) - 1);
Use `readlinkat` via #321.

2020-11-26 22:18 UTC, BenBE commented
Checking if all processes in `/proc` have a `cwd` symlink:
```bash
bash -c 'for a in /proc/*/; do [ -e $a/cwd ] || echo $a; done' # as root
```
Returns only non-PID directories for me.

IF you can read the symlink you should always get a non-empty string back. Thus `NULL` might act as a `no perm` marker. Haven't checked for processes running in different FS namespaces though.

2020-12-02 19:11 UTC, BenBE commented
Three issues I noticed while testing:

1. Overflows if path is too long (causes mis-alignment).
2. Regularly just shows `/proc/<pid>/fdinfo (deleted)` as cwd
3. `N/A` should be shadowed.

2020-12-02 19:24 UTC, cgzones commented
> * Overflows if path is too long (causes mis-alignment).

ideas?

> * Regularly just shows `/proc/<pid>/fdinfo (deleted)` as cwd

resolved

> * `N/A` should be shadowed.

resolved

2020-12-02 19:34 UTC, BenBE commented
> > * Overflows if path is too long (causes mis-alignment).
> 
> ideas?
> 
What about `xSnprintf(buffer, n, "%-25.25s", lp->cwd);` ???

2020-12-02 21:52 UTC, BenBE approved these changes

2020-12-03 08:21 UTC, merged