[WIP] Build rework and static build and musl support
htop-dev/htop pull request #412
Opened 2020-12-18 22:15 UTC by cgzones

2020-12-18 22:41 UTC, BenBE requested changes

2020-12-18 22:41 UTC, BenBE commented on scripts/build_musl_static.sh
> +    wget https://ftp.gnu.org/pub/gnu/ncurses/${NCURSES_FILE}
Please don't introduce any arbitrary random downloading into the build process.

Instead if this is missing fail with a meaningful error message.

2020-12-18 22:41 UTC, BenBE commented on scripts/build_musl_static.sh
> +    wget https://github.com/lm-sensors/lm-sensors/archive/${LMSENSORS_FILE}
dito.

2021-01-28 22:45 UTC, cgzones commented
Superseded by #482

2021-01-28 22:45 UTC, closed without merging