Added keybind 'N' for sorting by PID
htop-dev/htop pull request #413
Opened 2020-12-19 14:49 UTC by jakem72360

`N` key was selected, as it seems to be free and is backwards compatible with `top`.

2020-12-20 10:26 UTC, BenBE requested changes

2020-12-20 10:26 UTC, BenBE commented on Action.c
> +   { .key = "  F6 > .: ", .info = "select sort column" },
Resizing the key column causes too much unnecessary noise in the patch.

2020-12-20 10:26 UTC, BenBE commented on Action.c
> +         mvaddstr(line + item, 27, "threads");
Further resize-related noise.

2020-12-20 10:26 UTC, BenBE commented on Action.c
> +      mvaddstr(line + item, 50, helpRight[item].info);
dito.

2020-12-20 10:26 UTC, BenBE commented on Action.c
> +   { .key = "  F6 + -: ", .info = "expand/collapse tree" },
<kbd>F6</kbd> is no more.

2020-12-20 11:13 UTC, jakem72360 commented
What would your suggestion be? Adding the keybind to `key` in `helpLeft` would violate the leading space. Adding more padding causes the info section of the line to be cut off. Hardcoding coordinates is flimsy in general, and this seemed like the most logical solution.

I'm happy to change the patch, and am open to suggestions...

2020-12-20 14:27 UTC, BenBE commented
Instead of adding spaces everywhere I think it'd be less noise, if just the horizontal offset of everything was shifted to the right by one. The entry you need to actually update has two spaces at the front, thus you could fit it in there.

An alternative was to split the PMT line entirely (One function per line) and shuffle things from the left to the right (or vice versa) and add the N shortcut in a second commit.

2020-12-20 14:56 UTC, jakem72360 commented
I've updated it with changes only to the hardcoded X positions. I had assumed the leading spaces were desired, as they were present in both arrays.

Regarding splitting the sort functions onto multiple lines, I'll leave that decision to you. I think it looks better being one character wider, than a column being three lines longer. But like I said, it's up to you.

2020-12-21 13:48 UTC, fasterit commented
see `Action.c` a bit below your inserted line:
```
   keys['n'] = actionIncNext;
   keys['N'] = actionIncPrev;

```
Either we remove these bindings or we need to find something else to map to PID sorting.

2020-12-23 05:06 UTC, jakem72360 commented
I just noticed that. What do you think is best? If we remove the original bindings, we can preserve some compatibility with `top`. If we keep those bindings, I'd suggest the `D` key as it's the only letter in PID not already in use. For now, I'll update the PR with the `D` binding.

2020-12-23 10:53 UTC, fasterit commented
> I just noticed that. What do you think is best?
I think we should remove the old n / N bindings and the stale code they call.
I asked on IRC what fellow devs think about this. That would free the "N" key then for PID sorting.
o/ DLange

2020-12-23 16:27 UTC, jakem72360 commented
> I think we should remove the old n / N bindings and the stale code they call.
> I asked on IRC what fellow devs think about this. That would free the "N" key then for PID sorting.
> o/ DLange

Created #425 with proposal for code removal

2020-12-23 17:34 UTC, fasterit commented
Merged the patch (fixed back to using the N key) in the series up to f1463fd.

Thank you very much!

2020-12-23 17:34 UTC, closed without merging