Add possibility to hide function bar in MainPanel
htop-dev/htop pull request #440
Opened 2021-01-01 21:14 UTC by cgzones

Also fix the selection-cursor currently getting hidden by the FunctionBar when scrolling down.

2021-01-01 23:01 UTC, BenBE commented
Typo in commit message:
hight -> height

2021-01-01 23:03 UTC, BenBE requested changes
Overall typo: `hight` -> `height`

2021-01-01 23:03 UTC, BenBE commented on Panel.c
> +      } while (0)
indentation

2021-01-02 10:02 UTC, fasterit commented
Please make "Esc" toggle the function bar (and probably also the selection cursor bar).
Otherwise this is odd from a usability perspective.

People will very soon ask for a setting to hide the Function bar permanently if this PR gets merged, cf.  #168.
So you should probably implement that at the same time.

I'd personally prefer a simple setting to this Esc logic which may annoy the people that just want to get rid of the selection bar but keep those unsatisfied that want to always get rid of the Function bar.

2021-01-02 13:31 UTC, BenBE commented
I'd suggest not joining the ESC hiding of the cursor and the overall function bar hiding. IMO these are different things and should be kept separate. Based on demand in #168 I'd even argue that warrants a config option for the function bar hiding; though the ESC behaviour should be kept unimpeded by that setting.

2021-01-03 21:49 UTC, BenBE approved these changes
LGTM.

2021-01-04 22:12 UTC, merged