Darwin: scan thread information
htop-dev/htop pull request #546
Opened 2021-02-28 18:41 UTC by cgzones

Origin: https://github.com/hishamhm/htop/pull/848

Closes: #542

/cc @robaho @Karsten1987 @fasterit

2021-03-01 02:41 UTC, natoscott commented
@cgzones looks good to me.  Might be worth setting 'isThread = false;' in DarwinProcess_new instead of relying on the calloc there, for code clarity.  If that's not preferred and calloc is OK - which is fine by me - there's some other initializations-to-zero in that function that could be removed.

Also I wonder about the taskAccess field (not from your new code, but related to threads) - it seems like this field might cause incorrect behaviour if htop samples a process before it creates any threads - if it only creates threads later in its life, those threads would never be counted because this flag was set first time through.  If thats the case, I think it could be safely removed - it appears to be an optimization only, AFAICS.

2021-03-01 21:52 UTC, Karsten1987 reviewed
I honestly don't really see a difference with this change.

I've added a quick screenshot of my local output on my macbook, where the executable `a.out` contains two concurrently running pthreads. However, these are not visualized in any way.
![Screen Shot 2021-03-01 at 1 37 21 PM](https://user-images.githubusercontent.com/5419873/109563748-0ce54580-7a95-11eb-82ae-3a5c81b64b11.png)

For comparison, the same application built for Linux clearly shows the two running threads (highlighted in green):
![Screen Shot 2021-03-01 at 1 36 33 PM](https://user-images.githubusercontent.com/5419873/109563879-31412200-7a95-11eb-95d8-eae8c6f4192f.png)

2021-03-01 21:52 UTC, Karsten1987 commented on darwin/DarwinProcess.c
> +      ret = thread_info(thread_list[i], THREAD_EXTENDED_INFO_COUNT, (thread_info_t)thinfo, &thread_info_count);
are you sure that the `thinfo` struct is passed by copy and not by pointer-to? I've seen a couple of SO posts passing it in via `(thread_info_t) &thinfo`: https://stackoverflow.com/a/33414855/4583130

the same actually applies to the similar logic above for obtaining the `TASK_BASIC_INFO`.

2021-03-01 22:08 UTC, BenBE commented
Just a small tip: Press <kbd>Esc</kbd> once to hide the process list cursor. Also Tree Mode might be of help to group the threads optically below their parent.

2021-05-23 07:49 UTC, BenBE requested changes

2021-05-23 07:49 UTC, BenBE commented on darwin/DarwinProcess.h
> +   bool isThread;
Should be handled via global `Process::isUSerlandThread` field instead of introducing this new one.

2021-05-23 07:49 UTC, BenBE commented on darwin/DarwinProcess.c
>  }
Obsoleted by changes in #388.

2021-05-23 15:50 UTC, BenBE commented on darwin/DarwinProcess.c
> +void DarwinProcess_scanThreads(DarwinProcess* dp, DarwinProcessList *dpl) {
Consistent pointer alignment …

2021-05-23 15:50 UTC, BenBE commented on darwin/DarwinProcess.h
> +void DarwinProcess_scanThreads(DarwinProcess* dp, DarwinProcessList *dpl);
Pointer alignment …

2021-05-24 11:48 UTC, BenBE commented
Please check if this also fixes #622.

2023-04-08 15:44 UTC, Karrq commented
I checked out this lcoally and built it but I still don't see the threads, even running the tool with sudo.

On MBP M2 Ventura 13.3

2023-04-08 18:16 UTC, BenBE commented
Have you checked that your configuration has display of userland threads activated.

2023-04-09 09:28 UTC, Karrq commented
Yep I had unchecked "Hide userland process threads" and also tried toggling it on and off with `H` just to make sure and I don't see any change in my output, and I also tried tree/list mode...
I was trying to look at the threads of a specific process that I'm interested in as Activity Monitor only reports the number of threads (8), so I'm sure there are threads for that process.

(btw v3.2.2 also doesn't show threads per process, but I can see the total number of user threads under tasks)

2023-04-09 13:35 UTC, BenBE commented
Okay, strange. I can confirm this is somewhat strange behaviour. @cgzones Can you check your patch again?

2023-04-12 17:19 UTC, cgzones commented
Recent version of MacOS limit the access to foreign threads via `thread_info()`. I am not aware of an alternative API.
It might work though with a signed binary running as root (not tested).

2023-08-30 10:30 UTC, hashok commented
I've compiled `htop` from this branch on MacBook Pro Max M2 running macOS Ventura 13.5.1 (all updates installed as of 30-Aug-2023) and I *do see user land threads* 🎉 , but only when running `sudo htop`. I have _not_ signed the `htop` binary indeed. So it's definitely an improvement over the current `htop` version 3.2.2 from Homebrew.

2023-08-30 13:28 UTC, emadpres commented
I also just compiled [`cgzones:darwin_threads`](https://github.com/cgzones/htop/tree/darwin_threads) on M2 Max (McaOS 13.5.1), and I can confirm the threads are shown (only with `sudo`).

Not sure how relevant, the followings are broken:
1. refreshing
2. Tree structure (see `|`s)
3. scrolling


here is a side-by-side comparison of `htop` v3.2.2 with the compiled branch:
![Screenshot 2023-08-30 at 3 24 29 PM](https://github.com/htop-dev/htop/assets/2047884/9bb38102-fa5d-421e-aa91-13462b6a935c)

2023-08-31 11:34 UTC, emadpres commented
> Works on macOS 14.0 @emadpres Your PID is really high, too high for the tree.

What do you mean it's too high? That's what I get.

<img width="1015" alt="Screenshot 2023-08-31 at 1 34 10 PM" src="https://github.com/htop-dev/htop/assets/2047884/3921adbd-5355-4875-a3d0-e84b2805326e">

2023-08-31 11:37 UTC, BenBE commented
@cgzones Can you rebase? What'S missing to push this along?

2023-08-31 21:23 UTC, polluks commented
@emadpres I was talking about the width: Your PID have 7 digits but htop is fixed for 5 digits.
This seems to be a bug. However your system should not use 3 million processes in 4 days...

2023-09-13 15:45 UTC, cgzones commented
> What's missing to push this along?

Testing: check all threads are displayed, no memory is leaked, tree glitches.

(Only compile tested the latest rebase.)

2023-09-13 17:31 UTC, BenBE approved these changes
LGTM. No obvious memleaks.

Minor nitpick: Neither `identifer_info_count` nor `extended_info_count` are used or checked after their assignment through the call to `thread_info`, but access to at least the first item of the returned arrays is assumed.

2023-09-13 17:51 UTC, cgzones commented
> LGTM. No obvious memleaks.
> 
> Minor nitpick: Neither `identifer_info_count` nor `extended_info_count` are used or checked after their assignment through the call to `thread_info`, but access to at least the first item of the returned arrays is assumed.

The output parameters `identifer_info` and `extended_info` are not arrays, see https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/thread_info.html for API details.

2023-09-13 19:05 UTC, BenBE commented
> > LGTM. No obvious memleaks.
> > Minor nitpick: Neither `identifer_info_count` nor `extended_info_count` are used or checked after their assignment through the call to `thread_info`, but access to at least the first item of the returned arrays is assumed.
> 
> The output parameters `identifer_info` and `extended_info` are not arrays, see https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/thread_info.html for API details.

Ah, I see. So basically buffer sizes. In that case, at least checking for "a whole item was returned" should suffice. But as mentioned, that is somewhat nitpicky.

2023-10-08 22:07 UTC, BenBE commented
@cgzones Can you have a look at the PID auto-sizing issue? Likely missing the width update call for that column. Bugfix for that should get its own PR.

@fasterit Can you take a look at this PR, so we can push it along?

2024-04-19 15:36 UTC, dundee commented
Any update on this? Would be great to see threads on Mac!

2024-04-19 16:09 UTC, fasterit commented
@dundee: Did you test the [cgzones:darwin_threads](https://github.com/cgzones/htop/tree/darwin_threads) branch?

2024-04-20 21:32 UTC, dundee commented
@fasterit Yes, it works fine for me (using sudo).

2024-04-20 21:34 UTC, merged

2024-07-11 15:20 UTC, findepi commented
@cgzones @BenBE thanks for this PR!
Small question, which version this is/will be available in?
latest version from brew is 3.3.0 and doesn't show threads (even with sido). Current main branch built from source shows threads on my Mac (when run with sudo).

2024-07-11 16:28 UTC, BenBE commented
If your from-source build reports `3.3.0` you should re-run `autogen.sh`.

That aside: from the commit mentioned in the merge commit you can determine exactly when this landed, but I'd guess it's highly likely this was after 3.3.0 was released; thus this is probably not included in any release yet. Have a look at the milestone of this PR to check for which release it is planned.

2024-07-11 16:55 UTC, findepi commented
@BenBE apologies. i checked version wrong. my from-source build is `3.4.0-dev-3.3.0-144-gdb73229`.

> Have a look at the milestone of this PR to check for which release it is planned.

oh, i didn't notice that, but that's so nice.
looking forward to 3.4.0 release then. 
thanks!