Darwin: obtain CPU data using Intel Power Gadget
htop-dev/htop pull request #604
Opened 2021-04-17 18:29 UTC by danchr

The Power Gadget is a proprietary framework and driver from Intel, which allows user-space processes to query the CPU. Since the library might not be available at runtime, I've made the build system link against it weakly.

I've never contributed to `htop` before, and I'm not sure what your standards are, but I thought I'd post it here.

2021-04-17 23:47 UTC, BenBE requested changes

2021-04-17 23:47 UTC, BenBE commented on DisplayOptionsPanel.c
> +   #elif defined(HAVE_POWER_GADGET)
```suggestion
   #elif defined(HTOP_DARWIN) && defined(HAVE_POWER_GADGET)
```

2021-04-17 23:47 UTC, BenBE commented on configure.ac
> +esac
Check indentation. Should be 3 spaces per level.

2021-04-17 23:47 UTC, BenBE commented on darwin/DarwinProcessList.c
> +
No need for this blank line.

2021-04-17 23:47 UTC, BenBE commented on darwin/DarwinProcessList.c
> +   }
Try to reduce the nesting by e.g. inverting conditions and possibly early exiting.

2021-04-17 23:47 UTC, BenBE commented on darwin/DarwinProcessList.c
> +   this->cpu_sample = 0;
Implicit by `xCalloc` call from constructor of `this`.

2021-04-17 23:47 UTC, BenBE commented on darwin/DarwinProcessList.c
> +   }
May skip those braces. Cf. `STYLEGUIDE`.

2021-04-18 06:36 UTC, danchr commented
There, I think I got most of your comments?

2021-04-18 09:05 UTC, BenBE reviewed
Mostly LGTM.

2021-04-18 09:05 UTC, BenBE commented on darwin/DarwinProcessList.c
> +                                            &mean, &min, &max))
No need to wrap this IMHO.

2021-04-18 09:05 UTC, BenBE commented on darwin/DarwinProcessList.c
> +   }
No need for those braces.

2021-04-18 09:05 UTC, BenBE commented on darwin/DarwinProcessList.c
> +      }
Inconsistent braces.

2021-04-21 18:34 UTC, danchr commented
There, I think I got most of your comment. I also went through the code again to make sure that it handled the various failure cases correctly.

2021-04-21 20:15 UTC, BenBE requested changes

2021-04-21 20:15 UTC, BenBE commented on DisplayOptionsPanel.c
> +   #ifndef HTOP_DARWIN
Should use `defined` due to `#elif defined()`
```suggestion
   #if !defined(HTOP_DARWIN)
```

2021-04-21 20:15 UTC, BenBE commented on darwin/DarwinProcessList.h
> -
Two blanks after list of headers

2021-04-22 08:47 UTC, BenBE approved these changes
LGTM. Didn't test due to lack of Apple™ hardware …

2021-04-22 09:34 UTC, fasterit commented
As I read it the EULA of the "Intel Power Gadget" is incompatible with the GPLv2, e.g.
~~~text
"LICENSE GRANT:
Subject to all of the terms and conditions of this Agreement, Intel Corporation ("Intel") grants to you a non-exclusive, non-transferable copyright license to use the Materials internally only.

and

LICENSE RESTRICTIONS:
You may not distribute, sublicense or transfer any components of the Materials and derivatives thereof to any third party."
~~~

I don't think we can commit this and make homebrew et al distribute it.

Probably better to write a frequency measurement loop as per https://stackoverflow.com/a/39951453 which points at https://github.com/cyring/CoreFreq/blob/master/corefreqd.c which is GPLv2. The Intel Software mentioned in this PR also disallows re-engineering per their EULA. So not a legal source of info, either.

2021-04-22 13:13 UTC, BenBE commented
Due to the licensing issues @fasterit mentioned, I'd suggest to close this issue. Risking license issues for downstream distributions would be a sad result of adding a feature and thus the opposite of what is intended.

While there are ways to work around static linking restrictions in GPLv2 I won't recommend making this PR a precedent. Thus I'll go ahead and close this PR. If the copyright and license situation for the used interfaces improves another go on its inclusion may well follow.

2021-04-22 13:13 UTC, closed without merging

2021-04-23 11:25 UTC, danchr commented
Fair enough — I actually hadn't noticed that `htop` is GPL.