PCP: PCPMetric.[ch] Mdoule
htop-dev/htop pull request #743
Opened 2021-08-14 22:36 UTC by smalinux

Split the PCP Metric API (functions `Metric_*`) into their own module.
as @BenBE suggested.

2021-08-14 23:23 UTC, BenBE commented
Wondering if we should rename those from `Metric_*` to `PCPMetric_*` …

Would better match up with filenames and contained API names.

2021-08-14 23:30 UTC, BenBE requested changes

2021-08-14 23:30 UTC, BenBE commented on pcp/PCPMetric.c
> +(C) 2020-2021 Red Hat, Inc.  All Rights Reserved.
Note the copyright header for the other PCP source files.

2021-08-14 23:30 UTC, BenBE commented on pcp/PCPMetric.h
> +(C) 2020-2021 Red Hat, Inc.  All Rights Reserved.
Same copyright note …

2021-08-14 23:30 UTC, BenBE commented on pcp/PCPMetric.h
> +#include <sys/time.h>
Header order, cf. `STYLEGUIDE`

```suggestion
#include <ctype.h>
#include <stdbool.h>
#include <pcp/pmapi.h>
#include <sys/time.h>
```

2021-08-14 23:30 UTC, BenBE commented on pcp/PCPProcessList.c
> +#include "pcp/PCPMetric.h"
Header order …
```suggestion
#include "pcp/PCPMetric.h"
#include "pcp/PCPProcess.h"
```

2021-08-16 10:40 UTC, natoscott approved these changes
LGTM, thanks @smalinux

2021-08-16 15:22 UTC, BenBE approved these changes
LGTM.

2021-08-16 15:23 UTC, merged