Early program termination only from main()
htop-dev/htop pull request #833
Opened 2021-10-06 08:38 UTC by vasvolodimir

Fix for https://github.com/htop-dev/htop/issues/331

2021-10-06 08:53 UTC, BenBE requested changes

2021-10-06 08:53 UTC, BenBE commented on darwin/Platform.c
> +int Platform_init(void) {
Why change this, if the only return value is `0` anyways? If this shares the same semantics as `parseArguments` then a similar (or the same) enum should be used for marking the return value.

2021-10-06 08:53 UTC, BenBE commented on darwin/Platform.c
> +   return 0;
This return value doesn't make much sense, in particular as an int. IMHO `bool` (`stdbool.h`) would be better suited.

2021-10-06 08:53 UTC, BenBE commented on CommandLine.c
> +      return status < 0;
This does an implicit `bool`-to-`int` conversion and is kinda crude IMO.

2021-10-06 08:53 UTC, BenBE commented on CommandLine.c
> +            return 1;
Avoid magic numbers. Define a small enum for proper initialization outcomes and return the appropriate constant instead.

2021-10-06 08:53 UTC, BenBE commented on pcp/Platform.c
> +      Platform_done();
@natoscott Can you take a look here for PCP? Not sure if this call to `Platform_done()` is correct here.

2021-10-31 13:22 UTC, vasvolodimir commented
Hi @BenBE,
Rebase has done.

2021-10-31 13:33 UTC, BenBE requested changes

2021-10-31 13:33 UTC, BenBE commented on CommandLine.c
> +   CommandLineSettings flags;
Better to not leave things uninitialized here.
```suggestion
   CommandLineStatus status = STATUS_OK;
   CommandLineSettings flags = 0;
```

2021-10-31 13:33 UTC, BenBE commented on CommandLine.c
> +   if (Platform_init() == false)
```suggestion
   if (!Platform_init())
```

2021-10-31 13:54 UTC, BenBE approved these changes

2021-10-31 14:07 UTC, merged