IOMeters: rework initial display
htop-dev/htop pull request #883
Opened 2021-12-05 18:12 UTC by cgzones

Show a non highlighted string at the start of htop, not the failure
text. Also with ncurses the maximum time between updates is 25.5
seconds, so an interval of 30 seconds can only be reached by pausing
htop externally.
Also the original fix only handled the text mode, not the bar mode.

Improves: 2977414d ("Discard stale information from DiskIO and NetworkIO meters")
Related: #860

2021-12-05 18:34 UTC, BenBE commented
This reverts the check for stale data that was intentionally added previously.

2021-12-05 18:49 UTC, cgzones commented
So the stale check is intended to after htop being paused (externally) is resumed avoid spikes in the graph meter?
Otherwise seeing the accumulated IO usage over that paused time frame makes sense to me.

2021-12-05 19:45 UTC, BenBE commented
> So the stale check is intended to after htop being paused (externally) is resumed avoid spikes in the graph meter? Otherwise seeing the accumulated IO usage over that paused time frame makes sense to me.

Exactly. Or when due to high system load the last update is to old and thus using this data is prone to produce a spike if those information were processed.

2021-12-06 22:40 UTC, BenBE requested changes
Changes in NetworkIO meter similar to DiskIO meter …

2021-12-06 22:40 UTC, BenBE commented on DiskIOMeter.c
> +static enum { S_DATA, S_INIT, S_NODATA, S_STALE } status = S_INIT;
Don't quite like this inline type declaration here. In particular due to the duplication with the other IO meter.

2021-12-06 22:40 UTC, BenBE commented on DiskIOMeter.c
> +      status = Platform_getDiskIO(&data) ? (cached_last_update == 0 ? S_INIT : S_DATA) : S_NODATA;
This is not the easiest LOC to read. What about writing the if blocks explicitly?

2021-12-06 22:40 UTC, BenBE commented on DiskIOMeter.c
> +      status = Platform_getDiskIO(&data) ? (cached_last_update == 0 ? S_INIT : S_DATA) : S_NODATA;
```suggestion
      if (!Platform_getDiskIO(&data))
         status = S_NODATA;
      else if (cached_last_update == 0)
         status = S_INIT;
      else if (passedTimeInMs > 30000)
         status = S_STALE;
      else
         status = S_DATA;
```

2021-12-08 15:11 UTC, BenBE reviewed
Minor naming issue, apart from that LGTM.

2021-12-08 15:11 UTC, BenBE commented on Meter.h
> +   STALE_RATESTATUS
I'd prefer to have the namespacing of those constants to be prefixed. This also aligns better with most of the remaining code (Meter.h being an exception here AFAICS.

```suggestion
   RATESTATUS_DATA,
   RATESTATUS_INIT,
   RATESTATUS_NODATA,
   RATESTATUS_STALE
```

2021-12-08 15:50 UTC, BenBE approved these changes

2021-12-08 18:08 UTC, merged

2021-12-08 18:44 UTC, eworm-de commented
Thanks a lot! 😊