RFC: dynmically adjust column width at runtime for specific fields
htop-dev/htop pull request #891
Opened 2021-12-09 17:18 UTC by cgzones

Adjust the column width for fields known to be large dynamically at each cycle to the longest value.

Also with the recent addition of multiple screens, over-long columns can be moved into their own screen.

2021-12-09 18:26 UTC, BenBE requested changes

2021-12-09 18:26 UTC, BenBE commented on linux/LinuxProcess.c
> +      break;
If you keep CGROUP and CCGROUP in one line you might as well keep SECATTR in one line too …

2021-12-09 18:26 UTC, BenBE commented on linux/LinuxProcessList.c
> +      Process_updateFieldWidth(CCGROUP, strlen(process->cgroup_short));
`CCGROUP` given by `process->cgroup_short` can be `NULL` in which case this is aliased to `process->cgroup`.

2021-12-09 18:26 UTC, BenBE commented on linux/LinuxProcessList.c
>     } else {
Missing call to `Process_updateFieldWidth` in the `else` branch …

2022-02-24 21:39 UTC, BenBE commented
Should also adjust CPU usage column for values above 10000% as of #947 …

2022-03-06 18:41 UTC, fasterit commented
LGTM

2022-03-06 18:56 UTC, merged