PCP: add File Descriptor Meter
htop-dev/htop pull request #992
Opened 2022-05-04 08:00 UTC by smalinux

Related: #990

Signed-off-by: Sohaib Mohamed <sohaib.amhmd@gmail.com>

2022-05-04 10:01 UTC, fasterit commented
You can get the same info from `/proc/sys/fs/file-nr` on a Linux system.
BSD has `sysctl kern.maxfiles` and `sysctl kern.openfiles`.
Why not implement it to work outside PCP as well?

2022-05-04 10:21 UTC, natoscott commented
> You can get the same info from `/proc/sys/fs/file-nr` on a Linux system (#990). BSD has `sysctl kern.maxfiles` and `sysctl kern.openfiles`. Why not implement it to work outside PCP as well?

I'm not sure what you mean @fasterit ... ?  @BenBE has already implemented it "outside of PCP" for Linux, and has started on the BSD code AIUI - meanwhile this code from @smalinux using the (existing) PCP metrics looks on the right path to me for the PCP backend.

2022-05-04 10:22 UTC, smalinux commented
@fasterit That is a good idea, but the problem with this way is that it always assumes that the information will be available live all the time.
In the PCP case, on the other hand, it does not assume that. PCP could read this data from some archive logs or be read from another target machine.
That's the power of PCP: https://pcp.readthedocs.io/en/latest/UAG/IntroductionToPcp.html

2022-05-04 10:22 UTC, natoscott commented
@smalinux looks like you have a build failure there?

2022-05-04 10:29 UTC, smalinux commented
@natoscott yes, because #990 is still not merged yet and there is no FileDescriptorMeter.ch
I tested it and after adding it to [myhtopsources](https://github.com/htop-dev/htop/pull/990#pullrequestreview-961455302) will work perfectly :)

2022-05-04 11:03 UTC, fasterit commented
> > You can get the same info from `/proc/sys/fs/file-nr` on a Linux system (#990). BSD has `sysctl kern.maxfiles` and `sysctl kern.openfiles`. Why not implement it to work outside PCP as well?
> 
> I'm not sure what you mean @fasterit ... ? @BenBE has already implemented it "outside of PCP" for Linux, and has started on the BSD code AIUI - meanwhile this code from @smalinux using the (existing) PCP metrics looks on the right path to me for the PCP backend.

I meant to make sure we have the same meter on all (supported) platforms.

2022-05-04 14:21 UTC, BenBE commented
> @natoscott yes, because #990 is still not merged yet […]

Just rebase onto my branch …

2022-05-04 16:21 UTC, BenBE requested changes

2022-05-04 16:21 UTC, BenBE commented on pcp/Platform.c
> +      *max = value.ull;
Shouldn't they be read from the same field in `value`? They got the same `PM_TYPE_32` as their type after all …

2022-05-04 16:42 UTC, Explorer09 commented on pcp/Platform.c
> +   *max = 65536;
I am not yet familiar with PCP platform, but would you please comment on where this magic number is from?

2022-05-04 16:55 UTC, smalinux commented
> > @natoscott yes, because #990 is still not merged yet […]
> 
> Just rebase onto my branch …

Done.

2022-05-10 04:01 UTC, natoscott commented on pcp/Platform.c
> +   *used = NAN;
Need to initialize max here... may as well use what @BenBE used for Linux.

`*max = 65536;`

2023-03-24 23:40 UTC, closed without merging